### ISSUE TITLE
set-azstorageBlobContent requires updated azure module

### ISSUE THREAD

**Issue by mikekano** [chlaplan/IaaS-Builder#1]
Line 674
Set-AzStorageBlobContent -Container $dsccontainer.Name -File .\DSC\Configuration.zip -Blob 'Configuration.zip' -Context $dsccontainer.Context -Force -Verbose -AsJob 

This failed until I updated the AZ modules. You might need to add a version check for this module to ensure it is updated. the older module didn't support the "-asjob" parameter.

**Comment by chlaplan** [comment]
Updated PS script to update Storage Module if needed.

**Comment by chlaplan** [comment]
Fixed
